base_url: https://www.stratus.co

# LOG INTO stratus.co AND COPY THIS FROM YOUR COOKIES OR HEADERS

c_user: USER_ID
xs: SESSION_KEY 
AWSALB: LOAD_BALANCING_TOKEN
AWSALBCORS: CORS_LOAD_BALANCING_TOKEN

# DEFINE TEST SETTINGS

num_req: NUM_REQUEST_TO_RUN
sleep: SECONDS_BETWEEN_REQUESTS

# DEFINE TESTS

tests:
      - page: Homepage
        auth: Public
        load: BAL
        path: /
      - page: Homepage
        auth: Public
        load: UNBAL
        path: /
      - page: Profile 
        auth: Auth 
        load: BAL
        path: /alexk
      - page: Profile 
        auth: Auth 
        load: UNBAL
        path: /alexk
      - page: Profile 
        auth: Public 
        load: BAL
        path: /alexk
